use_encoder: true
joint_ids_map: [3, 0, 9, 6, 4, 1, 10, 7, 5, 2, 11, 8]
stiffness: [25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0]
damping: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
default_joint_pos: [0.1, -0.1, 0.1, -0.1, 0.8, 0.8, 1.0, 1.0, -1.5, -1.5, -1.5, -1.5]

control_dt: 0.02

policy_path: "pre_train/himloco_lab/policy_2025.pt"

depth_camera:
  topic: "rt/depth_image"
  min_depth: 0.25
  max_depth: 10.0
  resolution: [64, 40]   # width, height – must match training crop
  encoder_path: "pre_train/depth_encoder/vae_pretrain_new.pth"
  feature_dim: 64
  device: "cpu"

commands:
  base_velocity:
    ranges:
      lin_vel_x: [-1.5, 1.5]
      lin_vel_y: [-1.0, 1.0]
      ang_vel_z: [-2.0, 2.0]
      heading: null

navigation:
  enabled: false
  switch_button: "X"
  command_rate_hz: 5.0
  fixed_target_position: [0.0, 5.0, 0.5]
  use_raw_actions: true
  action_scale: [1.0, 1.0, 1.0]
  action_offset: [0.0, 0.0, 0.0]
  policy_distr_type: "gaussian"
  policy_scaling: [2.0, 1.0, 2.0]
  policy_bias: [0.0, 0.0, 0.0]
  low_pass_filter:
    enabled: true
    alpha: [0.5, 0.5, 0.5]
  policy_path: "pre_train/navigation/policy.pt"
  device: "cpu"
  policy_input:
    base_lin_vel:
      clip: [-100, 100]
      scale: 1.0
    base_ang_vel:
      clip: [-100, 100]
      scale: 1.0
    projected_gravity:
      clip: [-100, 100]
      scale: 1.0
    nav_last_action:
      clip: [-100, 100]
      scale: 1.0
    target_position:
      clip: [-100, 100]
      scale: 1.0
    depth_image:
      clip: [-100, 100]
      scale: 1.0

actions:
  JointPositionAction:
    clip: [-100.0, 100.0]
    scale: 0.25

encoder_input:
  history_length: 6
  velocity_commands:
    clip: [-100, 100]
    scale: 1.0
  base_ang_vel:
    clip: [-100, 100]
    scale: 0.25
  projected_gravity:
    clip: [-100, 100]
    scale: 1.0
  joint_pos_rel:
    clip: [-100, 100]
    scale: 1.0
  joint_vel_rel:
    clip: [-100, 100]
    scale: 0.05
  last_action:
    clip: [-100, 100]
    scale: 1.0

policy_input:
  velocity_commands:
    clip: [-100, 100]
    scale: 1.0
  base_ang_vel:
    clip: [-100, 100]
    scale: 0.25
  projected_gravity:
    clip: [-100, 100]
    scale: 1.0
  joint_pos_rel:
    clip: [-100, 100]
    scale: 1.0
  joint_vel_rel:
    clip: [-100, 100]
    scale: 0.05
  last_action:
    clip: [-100, 100]
    scale: 1.0
  encoder_output:
    clip: [-100, 100]
    scale: 1.0

FixStand:
  kp: [60, 80, 80, 60, 80, 80, 60, 80, 80, 60, 80, 80]
  kd: [5, 4, 4, 5, 4, 4, 5, 4, 4, 5, 4, 4]
  ts: [0, 1, 2]
  qs:
    - []
    - [0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65]
    - [0.0, 0.8, -1.5, 0.0, 0.8, -1.5, 0.0, 0.8, -1.5, 0.0, 0.8, -1.5]
